### ISSUE TITLE
lz4json on FreeBSD: liblz4 IS installed but lz4.h is reportedly not found

### ISSUE THREAD

**Issue by grahamperrin** [andikleen/lz4json#1]
```text
# date ; uname -v
Sat 14 Oct 2017 15:07:48 BST
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
# pwd
/usr/home/grahamperrin/Documents/com/github/andikleen/lz4json/lz4json-master
# make
cc -g -O2 -Wall  lz4jsoncat.c -llz4 -o lz4jsoncat
lz4jsoncat.c:31:10: fatal error: 'lz4.h' file not found
#include "lz4.h"
         ^~~~~~~
1 error generated.
*** Error code 1

Stop.
make: stopped in /usr/home/grahamperrin/Documents/com/github/andikleen/lz4json/lz4json-master
# pkg info liblz4 | grep -i version
Version        : 1.8.0,1
# 
```

**Comment by grahamperrin** [comment]
@dmgk also maybe relevant: 

```text
$ pwd
/usr/local/lib
$ find . -name "*lz4*"
./liblz4.so.1.8.0
./liblz4.so
./liblz4.a
./liblz4.so.1
$ 
```

**Comment by andikleen** [comment]
On Sat, Oct 14, 2017 at 10:33:18AM -0700, Graham Perrin wrote:
> @dmgk also maybe relevant:
> 
> $ pwd
> /usr/local/lib
> $ find . -name "*lz4*"
> ./liblz4.so.1.8.0
> ./liblz4.so
> ./liblz4.a
> ./liblz4.so.1
> $

It looks like you didn't install the development headers. There should
be a include/lz4.h somewhere.

**Comment by grahamperrin** [comment]
Thanks, with additional help from IRC I found: 

`/usr/local/include/lz4.h` 

… and gained a reminder to use `gmake`. 

## Random bonus prize

A strangely picturesque view of the content of a `search.json.mozlz4` file after decoding with `lz4jsoncat`: 

![2017-10-15 18 48 50 grahamperrin momh167-gjp4-hpelitebook8570p-freebsd -documents-com-github-andikleen-lz4json-lz4json-master konsole](https://user-images.githubusercontent.com/192271/31587482-5e8bc274-b1da-11e7-9e71-edd20fdef61a.png)

I wonder about the letters _e c_. But I'll not raise an issue in GitHub `:-)`

**Comment by ruv** [comment]
It is just a flipped G letter in two parts (because of screen lines length and starting point). Actually, it is Google logo in image/x-icon format and base64 encoding.

**Comment by cnst** [comment]
@grahamperrin and anyone else looking for UNIX®, Mac OS X w/ MacPorts, FreeBSD or NetBSD support — I fixed this in my branch over at https://github.com/cnst/lz4json, see Pull Request #13, which has not been accepted, because it apparently offers no advantage for GNU/Linux.  (For OpenBSD, there's already a port in the ports tree at [`archivers/lz4json`](http://openbsd.su/ports/archivers/lz4json).)

**Comment by UnitedMarsupials** [comment]
FWIW, I just added the [FreeBSD port](https://www.freshports.org/archivers/lz4json/) of this little program.

@andikleen, please, take a look at the [patch-file included](https://cgit.freebsd.org/ports/tree/archivers/lz4json/files/patch-warnings) there and consider incorporating all/some of the hunks. Thank you!
