### ISSUE TITLE
Add a license file?

### ISSUE THREAD

**Issue by polyzen** [andikleen/lz4json#11]

**Comment by andikleen** [comment]
There's already one in the source code

 * Copyright (c) 2014 Intel Corporation
 * Author: Andi Kleen
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that: (1) source code distributions
 * retain the above copyright notice and this paragraph in its entirety, (2)
 * distributions including binary code include the above copyright notice and
 * this paragraph in its entirety in the documentation or other materials
 * provided with the distribution
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

**Comment by polyzen** [comment]
Noticed that and then updated the title. What license is this? The Debian packaging claims "BSD2-ish".
