### ISSUE TITLE
Error while executing the make command

### ISSUE THREAD

**Issue by AbhilashG001** [andikleen/lz4json#3]
Invoking the make command results in an error. The screenshot for the same is attached below.
<br>
**Screenshot -**

![screenshot from 2017-11-29 17-52-00](https://user-images.githubusercontent.com/20839661/33374909-0a82d2c2-d52e-11e7-9b6f-0b1a8d476093.png)

**Logs -**<br>
The error message can be found [here](https://gist.github.com/AbhilashG97/dcff80f29894d34181a5b8c80b6e7d85)

**Comment by AbhilashG001** [comment]
@andikleen, is this a valid issue or did I miss something ? Can you please help me out ? Thank you

**Comment by andikleen** [comment]
Does it work with?

cc -g -O2 lz4jsoncat.c -o lzjsoncat -llz4 

If not there must be something wrong with the liblz4, perhaps you got a non standard version. 

I have "liblz4-1.4.0"

**Comment by AbhilashG001** [comment]
@andikleen, 

```cc -g -O2 lz4jsoncat.c -o lzjsoncat -llz4```

This worked for me and and I was able to view the bookmark file. Thank you so much, I am grateful for your help.
